### ISSUE TITLE
Niepoprawnie użyty znacznik <img src='img.png' />

### ISSUE THREAD

**Issue by dzienisz** [BaccAry/daftacademy_frontend4begginers#1]
https://github.com/BaccAry/daftacademy_frontend4begginers/blob/47ac2b1036bc54c7325151f1e44f7ddd49b80594/index.htm#L18

Niepoprawnie użyty znacznik `<img src='img.png' />`

![zrzut ekranu 2018-11-14 o 15 18 58](https://user-images.githubusercontent.com/3521624/48488315-bd759f80-e820-11e8-87b1-fe27d9ab5733.png)

**Comment by dzienisz** [comment]
Brakuje też atrybutu `alt='opis obrazka'`. Istotne z punku SEO i disability.

**Comment by BaccAry** [comment]
Poprawione, dziękuję :)
